package team.union.nonbusiness.sys.model;

import java.util.Date;

public class ApiAccessLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_access_log.API_ACCESS_LOG_ID
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    private Long apiAccessLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_access_log.API_ACCESS_LOG_URL
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    private String apiAccessLogUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_access_log.API_ACCESS_LOG_TIME
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    private Date apiAccessLogTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_access_log.API_ACCESS_LOG_IP
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    private String apiAccessLogIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_access_log.API_ACCESS_LOG_ID
     *
     * @return the value of api_access_log.API_ACCESS_LOG_ID
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public Long getApiAccessLogId() {
        return apiAccessLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_access_log.API_ACCESS_LOG_ID
     *
     * @param apiAccessLogId the value for api_access_log.API_ACCESS_LOG_ID
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setApiAccessLogId(Long apiAccessLogId) {
        this.apiAccessLogId = apiAccessLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_access_log.API_ACCESS_LOG_URL
     *
     * @return the value of api_access_log.API_ACCESS_LOG_URL
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public String getApiAccessLogUrl() {
        return apiAccessLogUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_access_log.API_ACCESS_LOG_URL
     *
     * @param apiAccessLogUrl the value for api_access_log.API_ACCESS_LOG_URL
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setApiAccessLogUrl(String apiAccessLogUrl) {
        this.apiAccessLogUrl = apiAccessLogUrl == null ? null : apiAccessLogUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_access_log.API_ACCESS_LOG_TIME
     *
     * @return the value of api_access_log.API_ACCESS_LOG_TIME
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public Date getApiAccessLogTime() {
        return apiAccessLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_access_log.API_ACCESS_LOG_TIME
     *
     * @param apiAccessLogTime the value for api_access_log.API_ACCESS_LOG_TIME
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setApiAccessLogTime(Date apiAccessLogTime) {
        this.apiAccessLogTime = apiAccessLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_access_log.API_ACCESS_LOG_IP
     *
     * @return the value of api_access_log.API_ACCESS_LOG_IP
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public String getApiAccessLogIp() {
        return apiAccessLogIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_access_log.API_ACCESS_LOG_IP
     *
     * @param apiAccessLogIp the value for api_access_log.API_ACCESS_LOG_IP
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setApiAccessLogIp(String apiAccessLogIp) {
        this.apiAccessLogIp = apiAccessLogIp == null ? null : apiAccessLogIp.trim();
    }
}