package team.union.nonbusiness.sys.model;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import team.union.nonbusiness.com.interf.BaseCriteria;



public class ResourcesCriteria extends BaseCriteria{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public ResourcesCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andResourcesIdIsNull() {
			addCriterion("resources_id is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIdIsNotNull() {
			addCriterion("resources_id is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesIdEqualTo(Long value) {
			addCriterion("resources_id =", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotEqualTo(Long value) {
			addCriterion("resources_id <>", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdGreaterThan(Long value) {
			addCriterion("resources_id >", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("resources_id >=", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdLessThan(Long value) {
			addCriterion("resources_id <", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdLessThanOrEqualTo(Long value) {
			addCriterion("resources_id <=", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdIn(List<Long> values) {
			addCriterion("resources_id in", values, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotIn(List<Long> values) {
			addCriterion("resources_id not in", values, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdBetween(Long value1, Long value2) {
			addCriterion("resources_id between", value1, value2, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotBetween(Long value1, Long value2) {
			addCriterion("resources_id not between", value1, value2, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdIsNull() {
			addCriterion("resources_parent_id is null");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdIsNotNull() {
			addCriterion("resources_parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdEqualTo(Long value) {
			addCriterion("resources_parent_id =", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdNotEqualTo(Long value) {
			addCriterion("resources_parent_id <>", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdGreaterThan(Long value) {
			addCriterion("resources_parent_id >", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("resources_parent_id >=", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdLessThan(Long value) {
			addCriterion("resources_parent_id <", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdLessThanOrEqualTo(Long value) {
			addCriterion("resources_parent_id <=", value, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdIn(List<Long> values) {
			addCriterion("resources_parent_id in", values, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdNotIn(List<Long> values) {
			addCriterion("resources_parent_id not in", values, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdBetween(Long value1, Long value2) {
			addCriterion("resources_parent_id between", value1, value2, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesParentIdNotBetween(Long value1, Long value2) {
			addCriterion("resources_parent_id not between", value1, value2, "resourcesParentId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdIsNull() {
			addCriterion("resources_sort_id is null");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdIsNotNull() {
			addCriterion("resources_sort_id is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdEqualTo(Integer value) {
			addCriterion("resources_sort_id =", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdNotEqualTo(Integer value) {
			addCriterion("resources_sort_id <>", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdGreaterThan(Integer value) {
			addCriterion("resources_sort_id >", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("resources_sort_id >=", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdLessThan(Integer value) {
			addCriterion("resources_sort_id <", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdLessThanOrEqualTo(Integer value) {
			addCriterion("resources_sort_id <=", value, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdIn(List<Integer> values) {
			addCriterion("resources_sort_id in", values, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdNotIn(List<Integer> values) {
			addCriterion("resources_sort_id not in", values, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdBetween(Integer value1, Integer value2) {
			addCriterion("resources_sort_id between", value1, value2, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesSortIdNotBetween(Integer value1, Integer value2) {
			addCriterion("resources_sort_id not between", value1, value2, "resourcesSortId");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseIsNull() {
			addCriterion("resources_is_use is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseIsNotNull() {
			addCriterion("resources_is_use is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseEqualTo(Byte value) {
			addCriterion("resources_is_use =", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseNotEqualTo(Byte value) {
			addCriterion("resources_is_use <>", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseGreaterThan(Byte value) {
			addCriterion("resources_is_use >", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseGreaterThanOrEqualTo(Byte value) {
			addCriterion("resources_is_use >=", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseLessThan(Byte value) {
			addCriterion("resources_is_use <", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseLessThanOrEqualTo(Byte value) {
			addCriterion("resources_is_use <=", value, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseIn(List<Byte> values) {
			addCriterion("resources_is_use in", values, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseNotIn(List<Byte> values) {
			addCriterion("resources_is_use not in", values, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_use between", value1, value2, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsUseNotBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_use not between", value1, value2, "resourcesIsUse");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableIsNull() {
			addCriterion("resources_is_visable is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableIsNotNull() {
			addCriterion("resources_is_visable is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableEqualTo(Byte value) {
			addCriterion("resources_is_visable =", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableNotEqualTo(Byte value) {
			addCriterion("resources_is_visable <>", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableGreaterThan(Byte value) {
			addCriterion("resources_is_visable >", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableGreaterThanOrEqualTo(Byte value) {
			addCriterion("resources_is_visable >=", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableLessThan(Byte value) {
			addCriterion("resources_is_visable <", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableLessThanOrEqualTo(Byte value) {
			addCriterion("resources_is_visable <=", value, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableIn(List<Byte> values) {
			addCriterion("resources_is_visable in", values, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableNotIn(List<Byte> values) {
			addCriterion("resources_is_visable not in", values, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_visable between", value1, value2, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesIsVisableNotBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_visable not between", value1, value2, "resourcesIsVisable");
			return (Criteria) this;
		}

		public Criteria andResourcesNameIsNull() {
			addCriterion("resources_name is null");
			return (Criteria) this;
		}

		public Criteria andResourcesNameIsNotNull() {
			addCriterion("resources_name is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesNameEqualTo(String value) {
			addCriterion("resources_name =", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameNotEqualTo(String value) {
			addCriterion("resources_name <>", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameGreaterThan(String value) {
			addCriterion("resources_name >", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameGreaterThanOrEqualTo(String value) {
			addCriterion("resources_name >=", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameLessThan(String value) {
			addCriterion("resources_name <", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameLessThanOrEqualTo(String value) {
			addCriterion("resources_name <=", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameLike(String value) {
			addCriterion("resources_name like", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameNotLike(String value) {
			addCriterion("resources_name not like", value, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameIn(List<String> values) {
			addCriterion("resources_name in", values, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameNotIn(List<String> values) {
			addCriterion("resources_name not in", values, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameBetween(String value1, String value2) {
			addCriterion("resources_name between", value1, value2, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesNameNotBetween(String value1, String value2) {
			addCriterion("resources_name not between", value1, value2, "resourcesName");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateIsNull() {
			addCriterion("resources_create_date is null");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateIsNotNull() {
			addCriterion("resources_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateEqualTo(Date value) {
			addCriterion("resources_create_date =", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateNotEqualTo(Date value) {
			addCriterion("resources_create_date <>", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateGreaterThan(Date value) {
			addCriterion("resources_create_date >", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("resources_create_date >=", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateLessThan(Date value) {
			addCriterion("resources_create_date <", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("resources_create_date <=", value, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateIn(List<Date> values) {
			addCriterion("resources_create_date in", values, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateNotIn(List<Date> values) {
			addCriterion("resources_create_date not in", values, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateBetween(Date value1, Date value2) {
			addCriterion("resources_create_date between", value1, value2, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("resources_create_date not between", value1, value2, "resourcesCreateDate");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlIsNull() {
			addCriterion("resources_url is null");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlIsNotNull() {
			addCriterion("resources_url is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlEqualTo(String value) {
			addCriterion("resources_url =", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlNotEqualTo(String value) {
			addCriterion("resources_url <>", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlGreaterThan(String value) {
			addCriterion("resources_url >", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlGreaterThanOrEqualTo(String value) {
			addCriterion("resources_url >=", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlLessThan(String value) {
			addCriterion("resources_url <", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlLessThanOrEqualTo(String value) {
			addCriterion("resources_url <=", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlLike(String value) {
			addCriterion("resources_url like", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlNotLike(String value) {
			addCriterion("resources_url not like", value, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlIn(List<String> values) {
			addCriterion("resources_url in", values, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlNotIn(List<String> values) {
			addCriterion("resources_url not in", values, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlBetween(String value1, String value2) {
			addCriterion("resources_url between", value1, value2, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesUrlNotBetween(String value1, String value2) {
			addCriterion("resources_url not between", value1, value2, "resourcesUrl");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionIsNull() {
			addCriterion("resources_description is null");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionIsNotNull() {
			addCriterion("resources_description is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionEqualTo(String value) {
			addCriterion("resources_description =", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionNotEqualTo(String value) {
			addCriterion("resources_description <>", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionGreaterThan(String value) {
			addCriterion("resources_description >", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("resources_description >=", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionLessThan(String value) {
			addCriterion("resources_description <", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionLessThanOrEqualTo(String value) {
			addCriterion("resources_description <=", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionLike(String value) {
			addCriterion("resources_description like", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionNotLike(String value) {
			addCriterion("resources_description not like", value, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionIn(List<String> values) {
			addCriterion("resources_description in", values, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionNotIn(List<String> values) {
			addCriterion("resources_description not in", values, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionBetween(String value1, String value2) {
			addCriterion("resources_description between", value1, value2, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesDescriptionNotBetween(String value1, String value2) {
			addCriterion("resources_description not between", value1, value2, "resourcesDescription");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeIsNull() {
			addCriterion("resources_child_size is null");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeIsNotNull() {
			addCriterion("resources_child_size is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeEqualTo(Integer value) {
			addCriterion("resources_child_size =", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeNotEqualTo(Integer value) {
			addCriterion("resources_child_size <>", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeGreaterThan(Integer value) {
			addCriterion("resources_child_size >", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("resources_child_size >=", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeLessThan(Integer value) {
			addCriterion("resources_child_size <", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeLessThanOrEqualTo(Integer value) {
			addCriterion("resources_child_size <=", value, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeIn(List<Integer> values) {
			addCriterion("resources_child_size in", values, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeNotIn(List<Integer> values) {
			addCriterion("resources_child_size not in", values, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeBetween(Integer value1, Integer value2) {
			addCriterion("resources_child_size between", value1, value2, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesChildSizeNotBetween(Integer value1, Integer value2) {
			addCriterion("resources_child_size not between", value1, value2, "resourcesChildSize");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsIsNull() {
			addCriterion("resources_is_popedoms is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsIsNotNull() {
			addCriterion("resources_is_popedoms is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsEqualTo(Byte value) {
			addCriterion("resources_is_popedoms =", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsNotEqualTo(Byte value) {
			addCriterion("resources_is_popedoms <>", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsGreaterThan(Byte value) {
			addCriterion("resources_is_popedoms >", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsGreaterThanOrEqualTo(Byte value) {
			addCriterion("resources_is_popedoms >=", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsLessThan(Byte value) {
			addCriterion("resources_is_popedoms <", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsLessThanOrEqualTo(Byte value) {
			addCriterion("resources_is_popedoms <=", value, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsIn(List<Byte> values) {
			addCriterion("resources_is_popedoms in", values, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsNotIn(List<Byte> values) {
			addCriterion("resources_is_popedoms not in", values, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_popedoms between", value1, value2, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesIsPopedomsNotBetween(Byte value1, Byte value2) {
			addCriterion("resources_is_popedoms not between", value1, value2, "resourcesIsPopedoms");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberIsNull() {
			addCriterion("resources_level_number is null");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberIsNotNull() {
			addCriterion("resources_level_number is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberEqualTo(Integer value) {
			addCriterion("resources_level_number =", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberNotEqualTo(Integer value) {
			addCriterion("resources_level_number <>", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberGreaterThan(Integer value) {
			addCriterion("resources_level_number >", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("resources_level_number >=", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberLessThan(Integer value) {
			addCriterion("resources_level_number <", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberLessThanOrEqualTo(Integer value) {
			addCriterion("resources_level_number <=", value, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberIn(List<Integer> values) {
			addCriterion("resources_level_number in", values, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberNotIn(List<Integer> values) {
			addCriterion("resources_level_number not in", values, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberBetween(Integer value1, Integer value2) {
			addCriterion("resources_level_number between", value1, value2, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesLevelNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("resources_level_number not between", value1, value2, "resourcesLevelNumber");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdIsNull() {
			addCriterion("resources_full_id is null");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdIsNotNull() {
			addCriterion("resources_full_id is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdEqualTo(String value) {
			addCriterion("resources_full_id =", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdNotEqualTo(String value) {
			addCriterion("resources_full_id <>", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdGreaterThan(String value) {
			addCriterion("resources_full_id >", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdGreaterThanOrEqualTo(String value) {
			addCriterion("resources_full_id >=", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdLessThan(String value) {
			addCriterion("resources_full_id <", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdLessThanOrEqualTo(String value) {
			addCriterion("resources_full_id <=", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdLike(String value) {
			addCriterion("resources_full_id like", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdNotLike(String value) {
			addCriterion("resources_full_id not like", value, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdIn(List<String> values) {
			addCriterion("resources_full_id in", values, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdNotIn(List<String> values) {
			addCriterion("resources_full_id not in", values, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdBetween(String value1, String value2) {
			addCriterion("resources_full_id between", value1, value2, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullIdNotBetween(String value1, String value2) {
			addCriterion("resources_full_id not between", value1, value2, "resourcesFullId");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameIsNull() {
			addCriterion("resources_full_name is null");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameIsNotNull() {
			addCriterion("resources_full_name is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameEqualTo(String value) {
			addCriterion("resources_full_name =", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameNotEqualTo(String value) {
			addCriterion("resources_full_name <>", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameGreaterThan(String value) {
			addCriterion("resources_full_name >", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameGreaterThanOrEqualTo(String value) {
			addCriterion("resources_full_name >=", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameLessThan(String value) {
			addCriterion("resources_full_name <", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameLessThanOrEqualTo(String value) {
			addCriterion("resources_full_name <=", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameLike(String value) {
			addCriterion("resources_full_name like", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameNotLike(String value) {
			addCriterion("resources_full_name not like", value, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameIn(List<String> values) {
			addCriterion("resources_full_name in", values, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameNotIn(List<String> values) {
			addCriterion("resources_full_name not in", values, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameBetween(String value1, String value2) {
			addCriterion("resources_full_name between", value1, value2, "resourcesFullName");
			return (Criteria) this;
		}

		public Criteria andResourcesFullNameNotBetween(String value1, String value2) {
			addCriterion("resources_full_name not between", value1, value2, "resourcesFullName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table resources
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RESOURCES
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 26 22:51:28 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}