package team.union.nonbusiness.sys.model;


import java.util.Date;

public class Resources {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Long resourcesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_parent_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Long resourcesParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_sort_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Integer resourcesSortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_is_use
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Byte resourcesIsUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_is_visable
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Byte resourcesIsVisable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private String resourcesName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_create_date
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Date resourcesCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_url
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private String resourcesUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_description
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private String resourcesDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_child_size
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Integer resourcesChildSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_is_popedoms
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Byte resourcesIsPopedoms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_level_number
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private Integer resourcesLevelNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_full_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private String resourcesFullId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.resources_full_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	private String resourcesFullName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_id
	 * @return  the value of resources.resources_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Long getResourcesId() {
		return resourcesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_id
	 * @param resourcesId  the value for resources.resources_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesId(Long resourcesId) {
		this.resourcesId = resourcesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_parent_id
	 * @return  the value of resources.resources_parent_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Long getResourcesParentId() {
		return resourcesParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_parent_id
	 * @param resourcesParentId  the value for resources.resources_parent_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesParentId(Long resourcesParentId) {
		this.resourcesParentId = resourcesParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_sort_id
	 * @return  the value of resources.resources_sort_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Integer getResourcesSortId() {
		return resourcesSortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_sort_id
	 * @param resourcesSortId  the value for resources.resources_sort_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesSortId(Integer resourcesSortId) {
		this.resourcesSortId = resourcesSortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_is_use
	 * @return  the value of resources.resources_is_use
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Byte getResourcesIsUse() {
		return resourcesIsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_is_use
	 * @param resourcesIsUse  the value for resources.resources_is_use
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesIsUse(Byte resourcesIsUse) {
		this.resourcesIsUse = resourcesIsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_is_visable
	 * @return  the value of resources.resources_is_visable
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Byte getResourcesIsVisable() {
		return resourcesIsVisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_is_visable
	 * @param resourcesIsVisable  the value for resources.resources_is_visable
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesIsVisable(Byte resourcesIsVisable) {
		this.resourcesIsVisable = resourcesIsVisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_name
	 * @return  the value of resources.resources_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getResourcesName() {
		return resourcesName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_name
	 * @param resourcesName  the value for resources.resources_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName == null ? null : resourcesName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_create_date
	 * @return  the value of resources.resources_create_date
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Date getResourcesCreateDate() {
		return resourcesCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_create_date
	 * @param resourcesCreateDate  the value for resources.resources_create_date
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesCreateDate(Date resourcesCreateDate) {
		this.resourcesCreateDate = resourcesCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_url
	 * @return  the value of resources.resources_url
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getResourcesUrl() {
		return resourcesUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_url
	 * @param resourcesUrl  the value for resources.resources_url
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesUrl(String resourcesUrl) {
		this.resourcesUrl = resourcesUrl == null ? null : resourcesUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_description
	 * @return  the value of resources.resources_description
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getResourcesDescription() {
		return resourcesDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_description
	 * @param resourcesDescription  the value for resources.resources_description
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesDescription(String resourcesDescription) {
		this.resourcesDescription = resourcesDescription == null ? null : resourcesDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_child_size
	 * @return  the value of resources.resources_child_size
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Integer getResourcesChildSize() {
		return resourcesChildSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_child_size
	 * @param resourcesChildSize  the value for resources.resources_child_size
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesChildSize(Integer resourcesChildSize) {
		this.resourcesChildSize = resourcesChildSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_is_popedoms
	 * @return  the value of resources.resources_is_popedoms
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Byte getResourcesIsPopedoms() {
		return resourcesIsPopedoms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_is_popedoms
	 * @param resourcesIsPopedoms  the value for resources.resources_is_popedoms
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesIsPopedoms(Byte resourcesIsPopedoms) {
		this.resourcesIsPopedoms = resourcesIsPopedoms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_level_number
	 * @return  the value of resources.resources_level_number
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public Integer getResourcesLevelNumber() {
		return resourcesLevelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_level_number
	 * @param resourcesLevelNumber  the value for resources.resources_level_number
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesLevelNumber(Integer resourcesLevelNumber) {
		this.resourcesLevelNumber = resourcesLevelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_full_id
	 * @return  the value of resources.resources_full_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getResourcesFullId() {
		return resourcesFullId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_full_id
	 * @param resourcesFullId  the value for resources.resources_full_id
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesFullId(String resourcesFullId) {
		this.resourcesFullId = resourcesFullId == null ? null : resourcesFullId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.resources_full_name
	 * @return  the value of resources.resources_full_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public String getResourcesFullName() {
		return resourcesFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.resources_full_name
	 * @param resourcesFullName  the value for resources.resources_full_name
	 * @mbggenerated  Tue Dec 29 22:30:47 CST 2015
	 */
	public void setResourcesFullName(String resourcesFullName) {
		this.resourcesFullName = resourcesFullName == null ? null : resourcesFullName.trim();
	}
}