package team.union.nonbusiness.sys.model;


public class Roles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_parent_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private Long roleParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_is_use
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private Byte roleIsUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_child_size
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private Integer roleChildSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_full_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private String roleFullId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_full_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private String roleFullName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_description
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	private String roleDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_id
	 * @return  the value of roles.role_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_id
	 * @param roleId  the value for roles.role_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_parent_id
	 * @return  the value of roles.role_parent_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Long getRoleParentId() {
		return roleParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_parent_id
	 * @param roleParentId  the value for roles.role_parent_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleParentId(Long roleParentId) {
		this.roleParentId = roleParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_name
	 * @return  the value of roles.role_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_name
	 * @param roleName  the value for roles.role_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_is_use
	 * @return  the value of roles.role_is_use
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Byte getRoleIsUse() {
		return roleIsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_is_use
	 * @param roleIsUse  the value for roles.role_is_use
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleIsUse(Byte roleIsUse) {
		this.roleIsUse = roleIsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_child_size
	 * @return  the value of roles.role_child_size
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Integer getRoleChildSize() {
		return roleChildSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_child_size
	 * @param roleChildSize  the value for roles.role_child_size
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleChildSize(Integer roleChildSize) {
		this.roleChildSize = roleChildSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_full_id
	 * @return  the value of roles.role_full_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public String getRoleFullId() {
		return roleFullId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_full_id
	 * @param roleFullId  the value for roles.role_full_id
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleFullId(String roleFullId) {
		this.roleFullId = roleFullId == null ? null : roleFullId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_full_name
	 * @return  the value of roles.role_full_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public String getRoleFullName() {
		return roleFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_full_name
	 * @param roleFullName  the value for roles.role_full_name
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleFullName(String roleFullName) {
		this.roleFullName = roleFullName == null ? null : roleFullName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_description
	 * @return  the value of roles.role_description
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public String getRoleDescription() {
		return roleDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_description
	 * @param roleDescription  the value for roles.role_description
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription == null ? null : roleDescription.trim();
	}
}