package team.union.nonbusiness.sys.model;
import java.util.ArrayList;
import java.util.List;
import team.union.nonbusiness.com.interf.BaseCriteria;

public class RoleResourcesPopedomCriteria  extends BaseCriteria{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public RoleResourcesPopedomCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRoleResourcesIdIsNull() {
			addCriterion("role_resources_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdIsNotNull() {
			addCriterion("role_resources_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdEqualTo(Long value) {
			addCriterion("role_resources_id =", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdNotEqualTo(Long value) {
			addCriterion("role_resources_id <>", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdGreaterThan(Long value) {
			addCriterion("role_resources_id >", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_resources_id >=", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdLessThan(Long value) {
			addCriterion("role_resources_id <", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdLessThanOrEqualTo(Long value) {
			addCriterion("role_resources_id <=", value, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdIn(List<Long> values) {
			addCriterion("role_resources_id in", values, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdNotIn(List<Long> values) {
			addCriterion("role_resources_id not in", values, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdBetween(Long value1, Long value2) {
			addCriterion("role_resources_id between", value1, value2, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleResourcesIdNotBetween(Long value1, Long value2) {
			addCriterion("role_resources_id not between", value1, value2, "roleResourcesId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Long> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Long> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdIsNull() {
			addCriterion("resources_id is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIdIsNotNull() {
			addCriterion("resources_id is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesIdEqualTo(Long value) {
			addCriterion("resources_id =", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotEqualTo(Long value) {
			addCriterion("resources_id <>", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdGreaterThan(Long value) {
			addCriterion("resources_id >", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("resources_id >=", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdLessThan(Long value) {
			addCriterion("resources_id <", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdLessThanOrEqualTo(Long value) {
			addCriterion("resources_id <=", value, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdIn(List<Long> values) {
			addCriterion("resources_id in", values, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotIn(List<Long> values) {
			addCriterion("resources_id not in", values, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdBetween(Long value1, Long value2) {
			addCriterion("resources_id between", value1, value2, "resourcesId");
			return (Criteria) this;
		}

		public Criteria andResourcesIdNotBetween(Long value1, Long value2) {
			addCriterion("resources_id not between", value1, value2, "resourcesId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table role_resources_popedom
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROLE_RESOURCES_POPEDOM
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 26 22:25:21 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}