package team.union.nonbusiness.sys.model;


public class RoleResourcesPopedom {
	
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resources_popedom.role_resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	private Long roleResourcesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resources_popedom.role_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resources_popedom.resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	private Long resourcesId;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resources_popedom.role_resources_id
	 * @return  the value of role_resources_popedom.role_resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public Long getRoleResourcesId() {
		return roleResourcesId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resources_popedom.role_resources_id
	 * @param roleResourcesId  the value for role_resources_popedom.role_resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void setRoleResourcesId(Long roleResourcesId) {
		this.roleResourcesId = roleResourcesId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resources_popedom.role_id
	 * @return  the value of role_resources_popedom.role_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public Long getRoleId() {
		return roleId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resources_popedom.role_id
	 * @param roleId  the value for role_resources_popedom.role_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resources_popedom.resources_id
	 * @return  the value of role_resources_popedom.resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public Long getResourcesId() {
		return resourcesId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resources_popedom.resources_id
	 * @param resourcesId  the value for role_resources_popedom.resources_id
	 * @mbggenerated  Thu Dec 31 14:42:17 CST 2015
	 */
	public void setResourcesId(Long resourcesId) {
		this.resourcesId = resourcesId;
	}


	public RoleResourcesPopedom() {
		super();
	}


	public RoleResourcesPopedom(Long roleId, Long resourcesId) {
		this.roleId = roleId;
		this.resourcesId = resourcesId;
	}
	
	
	public RoleResourcesPopedom(Long roleResourcesId, Long roleId,
			Long resourcesId) {
		this.roleResourcesId = roleResourcesId;
		this.roleId = roleId;
		this.resourcesId = resourcesId;
	}
}