package team.union.nonbusiness.sys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import team.union.nonbusiness.com.interf.BaseCriteria;

public class UserInRolesCriteria extends BaseCriteria{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public UserInRolesCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserInRoleIdIsNull() {
			addCriterion("user_in_role_id is null");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdIsNotNull() {
			addCriterion("user_in_role_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdEqualTo(Long value) {
			addCriterion("user_in_role_id =", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdNotEqualTo(Long value) {
			addCriterion("user_in_role_id <>", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdGreaterThan(Long value) {
			addCriterion("user_in_role_id >", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_in_role_id >=", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdLessThan(Long value) {
			addCriterion("user_in_role_id <", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("user_in_role_id <=", value, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdIn(List<Long> values) {
			addCriterion("user_in_role_id in", values, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdNotIn(List<Long> values) {
			addCriterion("user_in_role_id not in", values, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdBetween(Long value1, Long value2) {
			addCriterion("user_in_role_id between", value1, value2, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andUserInRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("user_in_role_id not between", value1, value2, "userInRoleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Long> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Long> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andOpDateIsNull() {
			addCriterion("op_date is null");
			return (Criteria) this;
		}

		public Criteria andOpDateIsNotNull() {
			addCriterion("op_date is not null");
			return (Criteria) this;
		}

		public Criteria andOpDateEqualTo(Date value) {
			addCriterion("op_date =", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateNotEqualTo(Date value) {
			addCriterion("op_date <>", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateGreaterThan(Date value) {
			addCriterion("op_date >", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateGreaterThanOrEqualTo(Date value) {
			addCriterion("op_date >=", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateLessThan(Date value) {
			addCriterion("op_date <", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateLessThanOrEqualTo(Date value) {
			addCriterion("op_date <=", value, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateIn(List<Date> values) {
			addCriterion("op_date in", values, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateNotIn(List<Date> values) {
			addCriterion("op_date not in", values, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateBetween(Date value1, Date value2) {
			addCriterion("op_date between", value1, value2, "opDate");
			return (Criteria) this;
		}

		public Criteria andOpDateNotBetween(Date value1, Date value2) {
			addCriterion("op_date not between", value1, value2, "opDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_in_roles
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_IN_ROLES
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 06 21:54:34 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}