package team.union.sys_sp.sys.model;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import team.union.sys_sp.com.interf.BaseCriteria;

public class AccountCriteria extends BaseCriteria{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public AccountCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(Long value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(Long value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(Long value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(Long value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(Long value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<Long> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<Long> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(Long value1, Long value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(Long value1, Long value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameIsNull() {
			addCriterion("account_login_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameIsNotNull() {
			addCriterion("account_login_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameEqualTo(String value) {
			addCriterion("account_login_name =", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameNotEqualTo(String value) {
			addCriterion("account_login_name <>", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameGreaterThan(String value) {
			addCriterion("account_login_name >", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("account_login_name >=", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameLessThan(String value) {
			addCriterion("account_login_name <", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameLessThanOrEqualTo(String value) {
			addCriterion("account_login_name <=", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameLike(String value) {
			addCriterion("account_login_name like", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameNotLike(String value) {
			addCriterion("account_login_name not like", value, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameIn(List<String> values) {
			addCriterion("account_login_name in", values, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameNotIn(List<String> values) {
			addCriterion("account_login_name not in", values, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameBetween(String value1, String value2) {
			addCriterion("account_login_name between", value1, value2, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginNameNotBetween(String value1, String value2) {
			addCriterion("account_login_name not between", value1, value2, "accountLoginName");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordIsNull() {
			addCriterion("account_login_password is null");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordIsNotNull() {
			addCriterion("account_login_password is not null");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordEqualTo(String value) {
			addCriterion("account_login_password =", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordNotEqualTo(String value) {
			addCriterion("account_login_password <>", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordGreaterThan(String value) {
			addCriterion("account_login_password >", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("account_login_password >=", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordLessThan(String value) {
			addCriterion("account_login_password <", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordLessThanOrEqualTo(String value) {
			addCriterion("account_login_password <=", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordLike(String value) {
			addCriterion("account_login_password like", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordNotLike(String value) {
			addCriterion("account_login_password not like", value, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordIn(List<String> values) {
			addCriterion("account_login_password in", values, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordNotIn(List<String> values) {
			addCriterion("account_login_password not in", values, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordBetween(String value1, String value2) {
			addCriterion("account_login_password between", value1, value2, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccountLoginPasswordNotBetween(String value1, String value2) {
			addCriterion("account_login_password not between", value1, value2, "accountLoginPassword");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeIsNull() {
			addCriterion("accuont_create_time is null");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeIsNotNull() {
			addCriterion("accuont_create_time is not null");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeEqualTo(Date value) {
			addCriterion("accuont_create_time =", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeNotEqualTo(Date value) {
			addCriterion("accuont_create_time <>", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeGreaterThan(Date value) {
			addCriterion("accuont_create_time >", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("accuont_create_time >=", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeLessThan(Date value) {
			addCriterion("accuont_create_time <", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("accuont_create_time <=", value, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeIn(List<Date> values) {
			addCriterion("accuont_create_time in", values, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeNotIn(List<Date> values) {
			addCriterion("accuont_create_time not in", values, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeBetween(Date value1, Date value2) {
			addCriterion("accuont_create_time between", value1, value2, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccuontCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("accuont_create_time not between", value1, value2, "accuontCreateTime");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseIsNull() {
			addCriterion("account_is_use is null");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseIsNotNull() {
			addCriterion("account_is_use is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseEqualTo(Byte value) {
			addCriterion("account_is_use =", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseNotEqualTo(Byte value) {
			addCriterion("account_is_use <>", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseGreaterThan(Byte value) {
			addCriterion("account_is_use >", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseGreaterThanOrEqualTo(Byte value) {
			addCriterion("account_is_use >=", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseLessThan(Byte value) {
			addCriterion("account_is_use <", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseLessThanOrEqualTo(Byte value) {
			addCriterion("account_is_use <=", value, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseIn(List<Byte> values) {
			addCriterion("account_is_use in", values, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseNotIn(List<Byte> values) {
			addCriterion("account_is_use not in", values, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseBetween(Byte value1, Byte value2) {
			addCriterion("account_is_use between", value1, value2, "accountIsUse");
			return (Criteria) this;
		}

		public Criteria andAccountIsUseNotBetween(Byte value1, Byte value2) {
			addCriterion("account_is_use not between", value1, value2, "accountIsUse");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbggenerated  Mon Dec 28 17:14:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 28 17:14:31 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}