package team.union.sys_sp.sys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import team.union.sys_sp.com.interf.BaseCriteria;

public class ApiAccessLogCriteria extends BaseCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public ApiAccessLogCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApiAccessLogIdIsNull() {
            addCriterion("API_ACCESS_LOG_ID is null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdIsNotNull() {
            addCriterion("API_ACCESS_LOG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdEqualTo(Long value) {
            addCriterion("API_ACCESS_LOG_ID =", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdNotEqualTo(Long value) {
            addCriterion("API_ACCESS_LOG_ID <>", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdGreaterThan(Long value) {
            addCriterion("API_ACCESS_LOG_ID >", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("API_ACCESS_LOG_ID >=", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdLessThan(Long value) {
            addCriterion("API_ACCESS_LOG_ID <", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdLessThanOrEqualTo(Long value) {
            addCriterion("API_ACCESS_LOG_ID <=", value, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdIn(List<Long> values) {
            addCriterion("API_ACCESS_LOG_ID in", values, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdNotIn(List<Long> values) {
            addCriterion("API_ACCESS_LOG_ID not in", values, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdBetween(Long value1, Long value2) {
            addCriterion("API_ACCESS_LOG_ID between", value1, value2, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIdNotBetween(Long value1, Long value2) {
            addCriterion("API_ACCESS_LOG_ID not between", value1, value2, "apiAccessLogId");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlIsNull() {
            addCriterion("API_ACCESS_LOG_URL is null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlIsNotNull() {
            addCriterion("API_ACCESS_LOG_URL is not null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_URL =", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlNotEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_URL <>", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlGreaterThan(String value) {
            addCriterion("API_ACCESS_LOG_URL >", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlGreaterThanOrEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_URL >=", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlLessThan(String value) {
            addCriterion("API_ACCESS_LOG_URL <", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlLessThanOrEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_URL <=", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlLike(String value) {
            addCriterion("API_ACCESS_LOG_URL like", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlNotLike(String value) {
            addCriterion("API_ACCESS_LOG_URL not like", value, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlIn(List<String> values) {
            addCriterion("API_ACCESS_LOG_URL in", values, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlNotIn(List<String> values) {
            addCriterion("API_ACCESS_LOG_URL not in", values, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlBetween(String value1, String value2) {
            addCriterion("API_ACCESS_LOG_URL between", value1, value2, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogUrlNotBetween(String value1, String value2) {
            addCriterion("API_ACCESS_LOG_URL not between", value1, value2, "apiAccessLogUrl");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeIsNull() {
            addCriterion("API_ACCESS_LOG_TIME is null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeIsNotNull() {
            addCriterion("API_ACCESS_LOG_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeEqualTo(Date value) {
            addCriterion("API_ACCESS_LOG_TIME =", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeNotEqualTo(Date value) {
            addCriterion("API_ACCESS_LOG_TIME <>", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeGreaterThan(Date value) {
            addCriterion("API_ACCESS_LOG_TIME >", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("API_ACCESS_LOG_TIME >=", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeLessThan(Date value) {
            addCriterion("API_ACCESS_LOG_TIME <", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeLessThanOrEqualTo(Date value) {
            addCriterion("API_ACCESS_LOG_TIME <=", value, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeIn(List<Date> values) {
            addCriterion("API_ACCESS_LOG_TIME in", values, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeNotIn(List<Date> values) {
            addCriterion("API_ACCESS_LOG_TIME not in", values, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeBetween(Date value1, Date value2) {
            addCriterion("API_ACCESS_LOG_TIME between", value1, value2, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogTimeNotBetween(Date value1, Date value2) {
            addCriterion("API_ACCESS_LOG_TIME not between", value1, value2, "apiAccessLogTime");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpIsNull() {
            addCriterion("API_ACCESS_LOG_IP is null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpIsNotNull() {
            addCriterion("API_ACCESS_LOG_IP is not null");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_IP =", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpNotEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_IP <>", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpGreaterThan(String value) {
            addCriterion("API_ACCESS_LOG_IP >", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpGreaterThanOrEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_IP >=", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpLessThan(String value) {
            addCriterion("API_ACCESS_LOG_IP <", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpLessThanOrEqualTo(String value) {
            addCriterion("API_ACCESS_LOG_IP <=", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpLike(String value) {
            addCriterion("API_ACCESS_LOG_IP like", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpNotLike(String value) {
            addCriterion("API_ACCESS_LOG_IP not like", value, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpIn(List<String> values) {
            addCriterion("API_ACCESS_LOG_IP in", values, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpNotIn(List<String> values) {
            addCriterion("API_ACCESS_LOG_IP not in", values, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpBetween(String value1, String value2) {
            addCriterion("API_ACCESS_LOG_IP between", value1, value2, "apiAccessLogIp");
            return (Criteria) this;
        }

        public Criteria andApiAccessLogIpNotBetween(String value1, String value2) {
            addCriterion("API_ACCESS_LOG_IP not between", value1, value2, "apiAccessLogIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_access_log
     *
     * @mbggenerated do_not_delete_during_merge Thu May 21 15:23:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table api_access_log
     *
     * @mbggenerated Thu May 21 15:23:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}