package team.union.sys_sp.sys.model;

import java.util.ArrayList;
import java.util.List;
import team.union.sys_sp.com.interf.BaseCriteria;

public class RolesCriteria  extends BaseCriteria{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public RolesCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Long> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Long> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdIsNull() {
			addCriterion("role_parent_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdIsNotNull() {
			addCriterion("role_parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdEqualTo(Long value) {
			addCriterion("role_parent_id =", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdNotEqualTo(Long value) {
			addCriterion("role_parent_id <>", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdGreaterThan(Long value) {
			addCriterion("role_parent_id >", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_parent_id >=", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdLessThan(Long value) {
			addCriterion("role_parent_id <", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdLessThanOrEqualTo(Long value) {
			addCriterion("role_parent_id <=", value, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdIn(List<Long> values) {
			addCriterion("role_parent_id in", values, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdNotIn(List<Long> values) {
			addCriterion("role_parent_id not in", values, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdBetween(Long value1, Long value2) {
			addCriterion("role_parent_id between", value1, value2, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleParentIdNotBetween(Long value1, Long value2) {
			addCriterion("role_parent_id not between", value1, value2, "roleParentId");
			return (Criteria) this;
		}

		public Criteria andRoleNameIsNull() {
			addCriterion("role_name is null");
			return (Criteria) this;
		}

		public Criteria andRoleNameIsNotNull() {
			addCriterion("role_name is not null");
			return (Criteria) this;
		}

		public Criteria andRoleNameEqualTo(String value) {
			addCriterion("role_name =", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameNotEqualTo(String value) {
			addCriterion("role_name <>", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameGreaterThan(String value) {
			addCriterion("role_name >", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
			addCriterion("role_name >=", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameLessThan(String value) {
			addCriterion("role_name <", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameLessThanOrEqualTo(String value) {
			addCriterion("role_name <=", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameLike(String value) {
			addCriterion("role_name like", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameNotLike(String value) {
			addCriterion("role_name not like", value, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameIn(List<String> values) {
			addCriterion("role_name in", values, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameNotIn(List<String> values) {
			addCriterion("role_name not in", values, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameBetween(String value1, String value2) {
			addCriterion("role_name between", value1, value2, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleNameNotBetween(String value1, String value2) {
			addCriterion("role_name not between", value1, value2, "roleName");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseIsNull() {
			addCriterion("role_is_use is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseIsNotNull() {
			addCriterion("role_is_use is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseEqualTo(Byte value) {
			addCriterion("role_is_use =", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseNotEqualTo(Byte value) {
			addCriterion("role_is_use <>", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseGreaterThan(Byte value) {
			addCriterion("role_is_use >", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseGreaterThanOrEqualTo(Byte value) {
			addCriterion("role_is_use >=", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseLessThan(Byte value) {
			addCriterion("role_is_use <", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseLessThanOrEqualTo(Byte value) {
			addCriterion("role_is_use <=", value, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseIn(List<Byte> values) {
			addCriterion("role_is_use in", values, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseNotIn(List<Byte> values) {
			addCriterion("role_is_use not in", values, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseBetween(Byte value1, Byte value2) {
			addCriterion("role_is_use between", value1, value2, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleIsUseNotBetween(Byte value1, Byte value2) {
			addCriterion("role_is_use not between", value1, value2, "roleIsUse");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeIsNull() {
			addCriterion("role_child_size is null");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeIsNotNull() {
			addCriterion("role_child_size is not null");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeEqualTo(Integer value) {
			addCriterion("role_child_size =", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeNotEqualTo(Integer value) {
			addCriterion("role_child_size <>", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeGreaterThan(Integer value) {
			addCriterion("role_child_size >", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("role_child_size >=", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeLessThan(Integer value) {
			addCriterion("role_child_size <", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeLessThanOrEqualTo(Integer value) {
			addCriterion("role_child_size <=", value, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeIn(List<Integer> values) {
			addCriterion("role_child_size in", values, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeNotIn(List<Integer> values) {
			addCriterion("role_child_size not in", values, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeBetween(Integer value1, Integer value2) {
			addCriterion("role_child_size between", value1, value2, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleChildSizeNotBetween(Integer value1, Integer value2) {
			addCriterion("role_child_size not between", value1, value2, "roleChildSize");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdIsNull() {
			addCriterion("role_full_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdIsNotNull() {
			addCriterion("role_full_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdEqualTo(String value) {
			addCriterion("role_full_id =", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdNotEqualTo(String value) {
			addCriterion("role_full_id <>", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdGreaterThan(String value) {
			addCriterion("role_full_id >", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdGreaterThanOrEqualTo(String value) {
			addCriterion("role_full_id >=", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdLessThan(String value) {
			addCriterion("role_full_id <", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdLessThanOrEqualTo(String value) {
			addCriterion("role_full_id <=", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdLike(String value) {
			addCriterion("role_full_id like", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdNotLike(String value) {
			addCriterion("role_full_id not like", value, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdIn(List<String> values) {
			addCriterion("role_full_id in", values, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdNotIn(List<String> values) {
			addCriterion("role_full_id not in", values, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdBetween(String value1, String value2) {
			addCriterion("role_full_id between", value1, value2, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullIdNotBetween(String value1, String value2) {
			addCriterion("role_full_id not between", value1, value2, "roleFullId");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameIsNull() {
			addCriterion("role_full_name is null");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameIsNotNull() {
			addCriterion("role_full_name is not null");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameEqualTo(String value) {
			addCriterion("role_full_name =", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameNotEqualTo(String value) {
			addCriterion("role_full_name <>", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameGreaterThan(String value) {
			addCriterion("role_full_name >", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameGreaterThanOrEqualTo(String value) {
			addCriterion("role_full_name >=", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameLessThan(String value) {
			addCriterion("role_full_name <", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameLessThanOrEqualTo(String value) {
			addCriterion("role_full_name <=", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameLike(String value) {
			addCriterion("role_full_name like", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameNotLike(String value) {
			addCriterion("role_full_name not like", value, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameIn(List<String> values) {
			addCriterion("role_full_name in", values, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameNotIn(List<String> values) {
			addCriterion("role_full_name not in", values, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameBetween(String value1, String value2) {
			addCriterion("role_full_name between", value1, value2, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleFullNameNotBetween(String value1, String value2) {
			addCriterion("role_full_name not between", value1, value2, "roleFullName");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionIsNull() {
			addCriterion("role_description is null");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionIsNotNull() {
			addCriterion("role_description is not null");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionEqualTo(String value) {
			addCriterion("role_description =", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionNotEqualTo(String value) {
			addCriterion("role_description <>", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionGreaterThan(String value) {
			addCriterion("role_description >", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("role_description >=", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionLessThan(String value) {
			addCriterion("role_description <", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionLessThanOrEqualTo(String value) {
			addCriterion("role_description <=", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionLike(String value) {
			addCriterion("role_description like", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionNotLike(String value) {
			addCriterion("role_description not like", value, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionIn(List<String> values) {
			addCriterion("role_description in", values, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionNotIn(List<String> values) {
			addCriterion("role_description not in", values, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionBetween(String value1, String value2) {
			addCriterion("role_description between", value1, value2, "roleDescription");
			return (Criteria) this;
		}

		public Criteria andRoleDescriptionNotBetween(String value1, String value2) {
			addCriterion("role_description not between", value1, value2, "roleDescription");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roles
	 * @mbggenerated  Tue Dec 29 13:18:55 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROLES
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 26 22:22:21 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}