package team.union.sys_sp.sys.model;


import java.util.Date;

public class UserInRoles {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_in_roles.user_in_role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	private Long userInRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_in_roles.role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_in_roles.user_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_in_roles.op_date
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	private Date opDate;





	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_in_roles.user_in_role_id
	 * @return  the value of user_in_roles.user_in_role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Long getUserInRoleId() {
		return userInRoleId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_in_roles.user_in_role_id
	 * @param userInRoleId  the value for user_in_roles.user_in_role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setUserInRoleId(Long userInRoleId) {
		this.userInRoleId = userInRoleId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_in_roles.role_id
	 * @return  the value of user_in_roles.role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Long getRoleId() {
		return roleId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_in_roles.role_id
	 * @param roleId  the value for user_in_roles.role_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_in_roles.user_id
	 * @return  the value of user_in_roles.user_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Long getUserId() {
		return userId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_in_roles.user_id
	 * @param userId  the value for user_in_roles.user_id
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}





	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_in_roles.op_date
	 * @return  the value of user_in_roles.op_date
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public Date getOpDate() {
		return opDate;
	}





	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_in_roles.op_date
	 * @param opDate  the value for user_in_roles.op_date
	 * @mbggenerated  Thu Dec 31 17:36:57 CST 2015
	 */
	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}





	public UserInRoles(Long userId, Long role_id) {
			
			this.userId = userId;
			this.roleId = role_id;
			
		}
	
	



	public UserInRoles() {
	}





	public UserInRoles(Long userInRoleId, Long userId, Long roleId,
			Date opDate) {
		
		this.userInRoleId = userInRoleId;
		this.userId = userId;
		this.roleId = roleId;
		this.opDate  = opDate;
	}
}