package team.union.business.activity.model;

import java.util.Date;
import java.util.List;

import team.union.nonbusiness.upload.model.NonbizUpload;

public class BisActivityDiscount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_start_time
     *
     * @mbggenerated
     */
    private Date activityStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_end_time
     *
     * @mbggenerated
     */
    private Date activityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_store_id
     *
     * @mbggenerated
     */
    private Long activityStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_pic
     *
     * @mbggenerated
     */
    private String activityPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_explain
     *
     * @mbggenerated
     */
    private String activityExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_status
     *
     * @mbggenerated
     */
    private Integer activityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.share_title
     *
     * @mbggenerated
     */
    private String shareTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.share_describe
     *
     * @mbggenerated
     */
    private String shareDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.share_pic
     *
     * @mbggenerated
     */
    private String sharePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bis_activity_discount.activity_creat_time
     *
     * @mbggenerated
     */
    private Date activityCreatTime;
    
    //活动图片
    private List<NonbizUpload> activityPicList;
    //分享图片
    private List<NonbizUpload> sharePicList;
    //活动开始时间String
    private String activityStartTimeStr;
    //活动结束时间string
    private String activityEndTimeStr;
    //活动店铺名称
    private String activityStoreName;
    

    public List<NonbizUpload> getActivityPicList() {
		return activityPicList;
	}

	public void setActivityPicList(List<NonbizUpload> activityPicList) {
		this.activityPicList = activityPicList;
	}

	public List<NonbizUpload> getSharePicList() {
		return sharePicList;
	}

	public void setSharePicList(List<NonbizUpload> sharePicList) {
		this.sharePicList = sharePicList;
	}

	public String getActivityStartTimeStr() {
		return activityStartTimeStr;
	}

	public void setActivityStartTimeStr(String activityStartTimeStr) {
		this.activityStartTimeStr = activityStartTimeStr;
	}

	public String getActivityEndTimeStr() {
		return activityEndTimeStr;
	}

	public void setActivityEndTimeStr(String activityEndTimeStr) {
		this.activityEndTimeStr = activityEndTimeStr;
	}

	public String getActivityStoreName() {
		return activityStoreName;
	}

	public void setActivityStoreName(String activityStoreName) {
		this.activityStoreName = activityStoreName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.id
     *
     * @return the value of bis_activity_discount.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.id
     *
     * @param id the value for bis_activity_discount.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_name
     *
     * @return the value of bis_activity_discount.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_name
     *
     * @param activityName the value for bis_activity_discount.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_start_time
     *
     * @return the value of bis_activity_discount.activity_start_time
     *
     * @mbggenerated
     */
    public Date getActivityStartTime() {
        return activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_start_time
     *
     * @param activityStartTime the value for bis_activity_discount.activity_start_time
     *
     * @mbggenerated
     */
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_end_time
     *
     * @return the value of bis_activity_discount.activity_end_time
     *
     * @mbggenerated
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_end_time
     *
     * @param activityEndTime the value for bis_activity_discount.activity_end_time
     *
     * @mbggenerated
     */
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_store_id
     *
     * @return the value of bis_activity_discount.activity_store_id
     *
     * @mbggenerated
     */
    public Long getActivityStoreId() {
        return activityStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_store_id
     *
     * @param activityStoreId the value for bis_activity_discount.activity_store_id
     *
     * @mbggenerated
     */
    public void setActivityStoreId(Long activityStoreId) {
        this.activityStoreId = activityStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_pic
     *
     * @return the value of bis_activity_discount.activity_pic
     *
     * @mbggenerated
     */
    public String getActivityPic() {
        return activityPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_pic
     *
     * @param activityPic the value for bis_activity_discount.activity_pic
     *
     * @mbggenerated
     */
    public void setActivityPic(String activityPic) {
        this.activityPic = activityPic == null ? null : activityPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_explain
     *
     * @return the value of bis_activity_discount.activity_explain
     *
     * @mbggenerated
     */
    public String getActivityExplain() {
        return activityExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_explain
     *
     * @param activityExplain the value for bis_activity_discount.activity_explain
     *
     * @mbggenerated
     */
    public void setActivityExplain(String activityExplain) {
        this.activityExplain = activityExplain == null ? null : activityExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_status
     *
     * @return the value of bis_activity_discount.activity_status
     *
     * @mbggenerated
     */
    public Integer getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_status
     *
     * @param activityStatus the value for bis_activity_discount.activity_status
     *
     * @mbggenerated
     */
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.share_title
     *
     * @return the value of bis_activity_discount.share_title
     *
     * @mbggenerated
     */
    public String getShareTitle() {
        return shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.share_title
     *
     * @param shareTitle the value for bis_activity_discount.share_title
     *
     * @mbggenerated
     */
    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle == null ? null : shareTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.share_describe
     *
     * @return the value of bis_activity_discount.share_describe
     *
     * @mbggenerated
     */
    public String getShareDescribe() {
        return shareDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.share_describe
     *
     * @param shareDescribe the value for bis_activity_discount.share_describe
     *
     * @mbggenerated
     */
    public void setShareDescribe(String shareDescribe) {
        this.shareDescribe = shareDescribe == null ? null : shareDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.share_pic
     *
     * @return the value of bis_activity_discount.share_pic
     *
     * @mbggenerated
     */
    public String getSharePic() {
        return sharePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.share_pic
     *
     * @param sharePic the value for bis_activity_discount.share_pic
     *
     * @mbggenerated
     */
    public void setSharePic(String sharePic) {
        this.sharePic = sharePic == null ? null : sharePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bis_activity_discount.activity_creat_time
     *
     * @return the value of bis_activity_discount.activity_creat_time
     *
     * @mbggenerated
     */
    public Date getActivityCreatTime() {
        return activityCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bis_activity_discount.activity_creat_time
     *
     * @param activityCreatTime the value for bis_activity_discount.activity_creat_time
     *
     * @mbggenerated
     */
    public void setActivityCreatTime(Date activityCreatTime) {
        this.activityCreatTime = activityCreatTime;
    }
}